### PR TITLE
Git/week2 homework

### PR DESCRIPTION
**Pull request by Gohar33**

### CODE REVIEW

**Comment by KavyaReddy732** [comment]
here are some modifications.
1.you need to edit the file in GitHub (i.e change 3 veggie name) in git/week2 branch.
2.the pull the changes in computer/terminal (command: git pull origin <branchname>)
3.changes should be merged to feature/veggies (cmd: git merge <branchname>)

**Comment by Gohar33** [comment]
Hi Kavya, thanks a lot. Just want to clarify, my PR is wrong or these are further modifications? Also, how can I edit anything in git/week2 branch if it's still in PR state?

**Comment by KavyaReddy732** [comment]
Hi Gohar, these are the changes and yes you can modify code when it’s in PR state. When you merge the two branches You’ll see this in PR.
7A980C50-EF18-4946-8160-AFAA694E4CE1

**Comment by Gohar33** [comment]
Hi Kavya, thanks but I still don't understand what's wrong with my existing PR and why should I do any changes if I already did your mentioned steps?

**Comment by KavyaReddy732** [comment]
You missed a step Gohar. That’s what I’m pointing. If you look into saide PR from your class you’ll get an idea. This is very important to know step for your project.

**Comment by Gohar33** [comment]
Thanks, Kavya, can you maybe tell me which step exactly I missed? I looked at Saide's PR and to me it looks the same as I did.

**Comment by Gohar33** [comment]
Hi Kavay, this is the history of commands I did with the homework before pushing it. Can you look and tell me which step I missed here? Thanks a lot 
Screenshot 2021-07-03 at 12 32 13

**Comment by KavyaReddy732** [comment]
After the last step you need to push the changes to feature/veggies

**Comment by Gohar33** [comment]
But I did that also. Here is a full list and the last 4 steps are add, commit and push to feature/veggies
Screenshot 2021-07-03 at 13 57 27

**Pull request merged**
